version: '3.9'

services:
  backend:
    build: ./backend
    container_name: devops-ai-agent-backend
    env_file:
      - ./backend/.env.example
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: devops_ai
      POSTGRES_PASSWORD: devops_ai
      POSTGRES_DB: devops_ai
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data: