apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-ai-agent.fullname" . }}
  labels:
    {{- include "devops-ai-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devops-ai-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "devops-ai-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: devops-ai-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.REDIS_PORT | quote }}
            - name: RABBITMQ_URL
              value: {{ .Values.env.RABBITMQ_URL | quote }}
          ports:
            - containerPort: 3000
              name: http