replicaCount: 1

image:
  repository: devops-ai-agent-backend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

env:
  DATABASE_URL: postgres://devops_ai:devops_ai@db:5432/devops_ai
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672