name: Deploy Nexus UI

on:
  push:
    branches:
      - main
    paths:
      - 'new-ui/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy UI files to server via rsync
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" rsync -avz --delete --progress -e "ssh -o StrictHostKeyChecking=no" \
            new-ui/ \
            "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.PROJECT_DIR }}"

      - name: Reload NGINX
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" \
            'sudo systemctl reload nginx || true'
