name: Deploy to Serbian server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH with password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 185.241.214.234         # or use ${{ secrets.SERVER_HOST }}
          username: root                # or use ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22                      # or use ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            # Define directory where the code should live on the server
            PROJECT_DIR="/root/devopsagent"

            # Clone or update the repo
            if [ ! -d "$PROJECT_DIR" ]; then
              mkdir -p "$PROJECT_DIR"
              git clone https://github.com/${{ github.repository }} "$PROJECT_DIR"
            else
              cd "$PROJECT_DIR"
              git pull origin main
            fi

            # Build and restart the backend container
            cd "$PROJECT_DIR/backend"
            docker build -t devops-ai-agent-backend .
            if [ $(docker ps -q -f name=devops-ai-agent-backend) ]; then
              docker stop devops-ai-agent-backend
              docker rm devops-ai-agent-backend
            fi
            docker run -d --name devops-ai-agent-backend -p 3000:3000 devops-ai-agent-backend

